// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: PB.proto

package handler

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// requests
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Age           int64                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Gender        bool                   `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_PB_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_PB_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *RegisterRequest) GetGender() bool {
	if x != nil {
		return x.Gender
	}
	return false
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_PB_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_PB_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverId    string                 `protobuf:"bytes,1,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=senderId,proto3" json:"senderId,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_PB_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_PB_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *SendMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShowMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContactId     string                 `protobuf:"bytes,2,opt,name=contactId,proto3" json:"contactId,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowMessagesRequest) Reset() {
	*x = ShowMessagesRequest{}
	mi := &file_PB_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowMessagesRequest) ProtoMessage() {}

func (x *ShowMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowMessagesRequest.ProtoReflect.Descriptor instead.
func (*ShowMessagesRequest) Descriptor() ([]byte, []int) {
	return file_PB_proto_rawDescGZIP(), []int{3}
}

func (x *ShowMessagesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShowMessagesRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *ShowMessagesRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_PB_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PB_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_PB_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_PB_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_PB_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_PB_proto_rawDescGZIP(), []int{5}
}

// responses
type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_PB_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_PB_proto_rawDescGZIP(), []int{6}
}

func (x *ReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserList      []string               `protobuf:"bytes,1,rep,name=userList,proto3" json:"userList,omitempty"`
	Status        []bool                 `protobuf:"varint,2,rep,packed,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResponse) Reset() {
	*x = UserListResponse{}
	mi := &file_PB_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResponse) ProtoMessage() {}

func (x *UserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResponse.ProtoReflect.Descriptor instead.
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return file_PB_proto_rawDescGZIP(), []int{7}
}

func (x *UserListResponse) GetUserList() []string {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *UserListResponse) GetStatus() []bool {
	if x != nil {
		return x.Status
	}
	return nil
}

type ShowMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []string               `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowMessagesResponse) Reset() {
	*x = ShowMessagesResponse{}
	mi := &file_PB_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowMessagesResponse) ProtoMessage() {}

func (x *ShowMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PB_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowMessagesResponse.ProtoReflect.Descriptor instead.
func (*ShowMessagesResponse) Descriptor() ([]byte, []int) {
	return file_PB_proto_rawDescGZIP(), []int{8}
}

func (x *ShowMessagesResponse) GetMessage() []string {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ShowMessagesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_PB_proto protoreflect.FileDescriptor

const file_PB_proto_rawDesc = "" +
	"\n" +
	"\bPB.proto\x12\x05proto\"s\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x03R\x03age\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\bR\x06gender\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"j\n" +
	"\x12SendMessageRequest\x12\x1e\n" +
	"\n" +
	"receiverId\x18\x01 \x01(\tR\n" +
	"receiverId\x12\x1a\n" +
	"\bsenderId\x18\x02 \x01(\tR\bsenderId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"Y\n" +
	"\x13ShowMessagesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tcontactId\x18\x02 \x01(\tR\tcontactId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"\x1f\n" +
	"\rLogoutRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\a\n" +
	"\x05Empty\"T\n" +
	"\x0eReportResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"F\n" +
	"\x10UserListResponse\x12\x1a\n" +
	"\buserList\x18\x01 \x03(\tR\buserList\x12\x16\n" +
	"\x06status\x18\x02 \x03(\bR\x06status\"J\n" +
	"\x14ShowMessagesResponse\x12\x18\n" +
	"\amessage\x18\x01 \x03(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\xf7\x02\n" +
	"\x0eChatbotService\x129\n" +
	"\bRegister\x12\x16.proto.RegisterRequest\x1a\x15.proto.ReportResponse\x123\n" +
	"\x05Login\x12\x13.proto.LoginRequest\x1a\x15.proto.ReportResponse\x125\n" +
	"\x06logout\x12\x14.proto.LogoutRequest\x1a\x15.proto.ReportResponse\x125\n" +
	"\fShowUserList\x12\f.proto.Empty\x1a\x17.proto.UserListResponse\x12?\n" +
	"\vSendMessage\x12\x19.proto.SendMessageRequest\x1a\x15.proto.ReportResponse\x12F\n" +
	"\vShowMessage\x12\x1a.proto.ShowMessagesRequest\x1a\x1b.proto.ShowMessagesResponseB\x13Z\x11hamrahTask1/protob\x06proto3"

var (
	file_PB_proto_rawDescOnce sync.Once
	file_PB_proto_rawDescData []byte
)

func file_PB_proto_rawDescGZIP() []byte {
	file_PB_proto_rawDescOnce.Do(func() {
		file_PB_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PB_proto_rawDesc), len(file_PB_proto_rawDesc)))
	})
	return file_PB_proto_rawDescData
}

var file_PB_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_PB_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: proto.RegisterRequest
	(*LoginRequest)(nil),         // 1: proto.LoginRequest
	(*SendMessageRequest)(nil),   // 2: proto.SendMessageRequest
	(*ShowMessagesRequest)(nil),  // 3: proto.ShowMessagesRequest
	(*LogoutRequest)(nil),        // 4: proto.LogoutRequest
	(*Empty)(nil),                // 5: proto.Empty
	(*ReportResponse)(nil),       // 6: proto.ReportResponse
	(*UserListResponse)(nil),     // 7: proto.UserListResponse
	(*ShowMessagesResponse)(nil), // 8: proto.ShowMessagesResponse
}
var file_PB_proto_depIdxs = []int32{
	0, // 0: proto.ChatbotService.Register:input_type -> proto.RegisterRequest
	1, // 1: proto.ChatbotService.Login:input_type -> proto.LoginRequest
	4, // 2: proto.ChatbotService.logout:input_type -> proto.LogoutRequest
	5, // 3: proto.ChatbotService.ShowUserList:input_type -> proto.Empty
	2, // 4: proto.ChatbotService.SendMessage:input_type -> proto.SendMessageRequest
	3, // 5: proto.ChatbotService.ShowMessage:input_type -> proto.ShowMessagesRequest
	6, // 6: proto.ChatbotService.Register:output_type -> proto.ReportResponse
	6, // 7: proto.ChatbotService.Login:output_type -> proto.ReportResponse
	6, // 8: proto.ChatbotService.logout:output_type -> proto.ReportResponse
	7, // 9: proto.ChatbotService.ShowUserList:output_type -> proto.UserListResponse
	6, // 10: proto.ChatbotService.SendMessage:output_type -> proto.ReportResponse
	8, // 11: proto.ChatbotService.ShowMessage:output_type -> proto.ShowMessagesResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PB_proto_init() }
func file_PB_proto_init() {
	if File_PB_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PB_proto_rawDesc), len(file_PB_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PB_proto_goTypes,
		DependencyIndexes: file_PB_proto_depIdxs,
		MessageInfos:      file_PB_proto_msgTypes,
	}.Build()
	File_PB_proto = out.File
	file_PB_proto_goTypes = nil
	file_PB_proto_depIdxs = nil
}
