// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: PB.proto

package handler

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatbotService_Register_FullMethodName     = "/proto.ChatbotService/Register"
	ChatbotService_Login_FullMethodName        = "/proto.ChatbotService/Login"
	ChatbotService_Logout_FullMethodName       = "/proto.ChatbotService/logout"
	ChatbotService_ShowUserList_FullMethodName = "/proto.ChatbotService/ShowUserList"
	ChatbotService_SendMessage_FullMethodName  = "/proto.ChatbotService/SendMessage"
	ChatbotService_ShowMessage_FullMethodName  = "/proto.ChatbotService/ShowMessage"
)

// ChatbotServiceClient is the client API for ChatbotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatbotServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	ShowUserList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserListResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	ShowMessage(ctx context.Context, in *ShowMessagesRequest, opts ...grpc.CallOption) (*ShowMessagesResponse, error)
}

type chatbotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatbotServiceClient(cc grpc.ClientConnInterface) ChatbotServiceClient {
	return &chatbotServiceClient{cc}
}

func (c *chatbotServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, ChatbotService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, ChatbotService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, ChatbotService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) ShowUserList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, ChatbotService_ShowUserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, ChatbotService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatbotServiceClient) ShowMessage(ctx context.Context, in *ShowMessagesRequest, opts ...grpc.CallOption) (*ShowMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowMessagesResponse)
	err := c.cc.Invoke(ctx, ChatbotService_ShowMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatbotServiceServer is the server API for ChatbotService service.
// All implementations must embed UnimplementedChatbotServiceServer
// for forward compatibility.
type ChatbotServiceServer interface {
	Register(context.Context, *RegisterRequest) (*ReportResponse, error)
	Login(context.Context, *LoginRequest) (*ReportResponse, error)
	Logout(context.Context, *LogoutRequest) (*ReportResponse, error)
	ShowUserList(context.Context, *Empty) (*UserListResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*ReportResponse, error)
	ShowMessage(context.Context, *ShowMessagesRequest) (*ShowMessagesResponse, error)
	mustEmbedUnimplementedChatbotServiceServer()
}

// UnimplementedChatbotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatbotServiceServer struct{}

func (UnimplementedChatbotServiceServer) Register(context.Context, *RegisterRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedChatbotServiceServer) Login(context.Context, *LoginRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedChatbotServiceServer) Logout(context.Context, *LogoutRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedChatbotServiceServer) ShowUserList(context.Context, *Empty) (*UserListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowUserList not implemented")
}
func (UnimplementedChatbotServiceServer) SendMessage(context.Context, *SendMessageRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatbotServiceServer) ShowMessage(context.Context, *ShowMessagesRequest) (*ShowMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShowMessage not implemented")
}
func (UnimplementedChatbotServiceServer) mustEmbedUnimplementedChatbotServiceServer() {}
func (UnimplementedChatbotServiceServer) testEmbeddedByValue()                        {}

// UnsafeChatbotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatbotServiceServer will
// result in compilation errors.
type UnsafeChatbotServiceServer interface {
	mustEmbedUnimplementedChatbotServiceServer()
}

func RegisterChatbotServiceServer(s grpc.ServiceRegistrar, srv ChatbotServiceServer) {
	// If the following call panics, it indicates UnimplementedChatbotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatbotService_ServiceDesc, srv)
}

func _ChatbotService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_ShowUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).ShowUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_ShowUserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).ShowUserList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatbotService_ShowMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServiceServer).ShowMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatbotService_ShowMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServiceServer).ShowMessage(ctx, req.(*ShowMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatbotService_ServiceDesc is the grpc.ServiceDesc for ChatbotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatbotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ChatbotService",
	HandlerType: (*ChatbotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ChatbotService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ChatbotService_Login_Handler,
		},
		{
			MethodName: "logout",
			Handler:    _ChatbotService_Logout_Handler,
		},
		{
			MethodName: "ShowUserList",
			Handler:    _ChatbotService_ShowUserList_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChatbotService_SendMessage_Handler,
		},
		{
			MethodName: "ShowMessage",
			Handler:    _ChatbotService_ShowMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "PB.proto",
}
